---
apiVersion: v1
kind: Namespace
metadata:
  name: test-workload-identity-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-cnrmsa
  namespace: test-workload-identity-ns
  annotations:
    "iam.gke.io/gcp-service-account": "cnrmsa@anthos-lab-6b57eb58.iam.gserviceaccount.com"
