---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: wi-gcp-sa
spec:
  displayName: wi-gcp-sa

---
apiVersion: v1
kind: Namespace
metadata:
  name: wi-k8s-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wi-k8s-sa
  namespace: wi-k8s-ns
  annotations:
    iam.gke.io/gcp-service-account: wi-gcp-sa@lab1-320219.iam.gserviceaccount.com

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: wi-iam-policy
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: wi-gcp-sa
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:lab1-320219.svc.id.goog[wi-k8s-ns/wi-k8s-sa]

---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: test-topic

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: wi-gcp-sa-policy-member
spec:
  # replace ${PROJECT_ID?} with your project name
  member: serviceAccount:wi-gcp-sa@$lab1-320219.iam.gserviceaccount.com
  role: roles/editor
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: test-topic
