---
apiVersion: v1
kind: Namespace
metadata:
  name: test-workload-identity-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-cnrmsa
  namespace: test-workload-identity-ns
  annotations:
    "iam.gke.io/gcp-service-account": "cnrmsa@anthos-lab-6b57eb58.iam.gserviceaccount.com"

---
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  googleServiceAccount: "cnrmsa@anthos-lab-6b57eb58.iam.gserviceaccount.com" 
  mode: cluster

---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: wp-db-3
  namespace: test-workload-identity-ns
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  settings:
    tier: db-f1-micro

---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: wordpress
  namespace: test-workload-identity-ns
spec:
  charset: utf8
  instanceRef:
    name: wp-db
