---
apiVersion: v1
kind: Namespace
metadata:
  name: test-workload-identity-ns

---
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  googleServiceAccount: "cnrmsa@anthos-lab-6b57eb58.iam.gserviceaccount.com" 
  mode: cluster

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: "testing3"
  annotations:
    cnrm.cloud.google.com/project-id: "anthos-lab-6b57eb58"
spec:
  displayName: "testing3"

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: iampolicy-workload-identity-sample
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: "cnrmsa"
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:anthos-lab-6b57eb58.svc.id.goog[test-workload-identity-ns/k8s-cnrmsa]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-cnrmsa
  namespace: test-workload-identity-ns
  annotations:
    "iam.gke.io/gcp-service-account": "cnrmsa@anthos-lab-6b57eb58.iam.gserviceaccount.com"
    
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: wp-db
  namespace: test-workload-identity-ns
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  settings:
    tier: db-f1-micro

---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: wordpress
  namespace: test-workload-identity-ns
spec:
  charset: utf8
  instanceRef:
    name: wp-db
