---
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  googleServiceAccount: "cnrmsa@anthos-lab-6b57eb58.iam.gserviceaccount.com" 
  mode: cluster

---
apiVersion: v1
kind: Namespace
metadata:
  name: test-workload-identity-ns

---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: wp-db-1646158076-1
  namespace: test-workload-identity-ns
  annotations:
    cnrm.cloud.google.com/project-id: "anthos-lab-6b57eb58"
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  settings:
    tier: db-f1-micro

---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: wordpress-1
  namespace: test-workload-identity-ns
  annotations:
    cnrm.cloud.google.com/project-id: "anthos-lab-6b57eb58"
spec:
  charset: utf8
  instanceRef:
    name: wp-db-1646158076-1
