---
apiVersion: v1
kind: Namespace
metadata:
  name: wi-k8s-ns-2

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wi-k8s-sa
  namespace: wi-k8s-ns-2

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: wi-gcp-sa
spec:
  displayName: wi-gcp-sa
